export const POKEMON_V2_API_URLS = {
  BASE_URL: 'https://pokeapi.co/api/v2',
  POKEMON: (idOrName: string | number) => `/pokemon/${idOrName}`,
  POKEMON_SPECIES: (idOrName: string | number) => `/pokemon-species/${idOrName}`,
  ABILITY: (idOrName: string | number) => `/ability/${idOrName}`,
  TYPE: (idOrName: string | number) => `/type/${idOrName}`,
  MOVE: (idOrName: string | number) => `/move/${idOrName}`,
  MOVE_CATEGORY: (idOrName: string | number) => `/move-category/${idOrName}`,
  MOVE_DAMAGE_CLASS: (idOrName: string | number) => `/move-damage-class/${idOrName}`,
  ITEM: (idOrName: string | number) => `/item/${idOrName}`,
  ITEM_CATEGORY: (idOrName: string | number) => `/item-category/${idOrName}`,
  ITEM_POCKET: (idOrName: string | number) => `/item-pocket/${idOrName}`,
  LOCATION: (idOrName: string | number) => `/location/${idOrName}`,
  LOCATION_AREA: (idOrName: string | number) => `/location-area/${idOrName}`,
  REGION: (idOrName: string | number) => `/region/${idOrName}`,
  EVOLUTION_CHAIN: (id: number) => `/evolution-chain/${id}`,
  GENERATION: (idOrName: string | number) => `/generation/${idOrName}`,
  GENDER: (idOrName: string | number) => `/gender/${idOrName}`,
  GROWTH_RATE: (idOrName: string | number) => `/growth-rate/${idOrName}`,
  NATURE: (idOrName: string | number) => `/nature/${idOrName}`,
  STAT: (idOrName: string | number) => `/stat/${idOrName}`,

  // List endpoints with pagination params
  POKEMON_LIST: '/pokemon',
  ABILITY_LIST: '/ability',
  TYPE_LIST: '/type',
  MOVE_LIST: '/move',
  ITEM_LIST: '/item',
  LOCATION_LIST: '/location',
  REGION_LIST: '/region',
  GENERATION_LIST: '/generation',
};