export const POKEMON_V2_API_URLS = {
  BASE_URL: 'https://pokeapi.co/api/v2',

  // Single resource endpoints (by id or name)
  POKEMON: (idOrName: string | number) => `/pokemon/${idOrName}`,
  POKEMON_SPECIES: (idOrName: string | number) => `/pokemon-species/${idOrName}`,
  ABILITY: (idOrName: string | number) => `/ability/${idOrName}`,
  TYPE: (idOrName: string | number) => `/type/${idOrName}`,
  MOVE: (idOrName: string | number) => `/move/${idOrName}`,
  MOVE_CATEGORY: (idOrName: string | number) => `/move-category/${idOrName}`,
  MOVE_DAMAGE_CLASS: (idOrName: string | number) => `/move-damage-class/${idOrName}`,
  ITEM: (idOrName: string | number) => `/item/${idOrName}`,
  ITEM_CATEGORY: (idOrName: string | number) => `/item-category/${idOrName}`,
  ITEM_POCKET: (idOrName: string | number) => `/item-pocket/${idOrName}`,
  LOCATION: (idOrName: string | number) => `/location/${idOrName}`,
  LOCATION_AREA: (idOrName: string | number) => `/location-area/${idOrName}`,
  REGION: (idOrName: string | number) => `/region/${idOrName}`,
  EVOLUTION_CHAIN: (id: number) => `/evolution-chain/${id}`,
  GENERATION: (idOrName: string | number) => `/generation/${idOrName}`,
  GENDER: (idOrName: string | number) => `/gender/${idOrName}`,
  GROWTH_RATE: (idOrName: string | number) => `/growth-rate/${idOrName}`,
  NATURE: (idOrName: string | number) => `/nature/${idOrName}`,
  STAT: (idOrName: string | number) => `/stat/${idOrName}`,
  EGG_GROUP: (idOrName: string | number) => `/egg-group/${idOrName}`,
  LANGUAGE: (idOrName: string | number) => `/language/${idOrName}`,
  BERRY: (idOrName: string | number) => `/berry/${idOrName}`,
  BERRY_FIRMNESS: (idOrName: string | number) => `/berry-firmness/${idOrName}`,
  BERRY_FLAVOR: (idOrName: string | number) => `/berry-flavor/${idOrName}`,
  CONTEST_TYPE: (idOrName: string | number) => `/contest-type/${idOrName}`,
  CONTEST_EFFECT: (idOrName: string | number) => `/contest-effect/${idOrName}`,
  SUPER_CONTEST_EFFECT: (idOrName: string | number) => `/super-contest-effect/${idOrName}`,
  ENCOUNTER_METHOD: (idOrName: string | number) => `/encounter-method/${idOrName}`,
  ENCOUNTER_CONDITION: (idOrName: string | number) => `/encounter-condition/${idOrName}`,
  ENCOUNTER_CONDITION_VALUE: (idOrName: string | number) => `/encounter-condition-value/${idOrName}`,
  PAL_PARK_AREA: (idOrName: string | number) => `/pal-park-area/${idOrName}`,
  POKEMON_COLOR: (idOrName: string | number) => `/pokemon-color/${idOrName}`,
  POKEMON_FORM: (idOrName: string | number) => `/pokemon-form/${idOrName}`,
  POKEMON_HABITAT: (idOrName: string | number) => `/pokemon-habitat/${idOrName}`,
  POKEMON_SHAPE: (idOrName: string | number) => `/pokemon-shape/${idOrName}`,
  VERSION: (idOrName: string | number) => `/version/${idOrName}`,
  VERSION_GROUP: (idOrName: string | number) => `/version-group/${idOrName}`,
  EFFECT: (idOrName: string | number) => `/effect/${idOrName}`,
  EFFECT_CHANCE: (idOrName: string | number) => `/effect-chains/${idOrName}`,

  // List endpoints (for paginated lists)
  POKEMON_LIST: '/pokemon',
  POKEMON_SPECIES_LIST: '/pokemon-species',
  ABILITY_LIST: '/ability',
  TYPE_LIST: '/type',
  MOVE_LIST: '/move',
  MOVE_CATEGORY_LIST: '/move-category',
  MOVE_DAMAGE_CLASS_LIST: '/move-damage-class',
  ITEM_LIST: '/item',
  ITEM_CATEGORY_LIST: '/item-category',
  ITEM_POCKET_LIST: '/item-pocket',
  LOCATION_LIST: '/location',
  LOCATION_AREA_LIST: '/location-area',
  REGION_LIST: '/region',
  EVOLUTION_CHAIN_LIST: '/evolution-chain',
  GENERATION_LIST: '/generation',
  GENDER_LIST: '/gender',
  GROWTH_RATE_LIST: '/growth-rate',
  NATURE_LIST: '/nature',
  STAT_LIST: '/stat',
  EGG_GROUP_LIST: '/egg-group',
  LANGUAGE_LIST: '/language',
  BERRY_LIST: '/berry',
  BERRY_FIRMNESS_LIST: '/berry-firmness',
  BERRY_FLAVOR_LIST: '/berry-flavor',
  CONTEST_TYPE_LIST: '/contest-type',
  CONTEST_EFFECT_LIST: '/contest-effect',
  SUPER_CONTEST_EFFECT_LIST: '/super-contest-effect',
  ENCOUNTER_METHOD_LIST: '/encounter-method',
  ENCOUNTER_CONDITION_LIST: '/encounter-condition',
  ENCOUNTER_CONDITION_VALUE_LIST: '/encounter-condition-value',
  PAL_PARK_AREA_LIST: '/pal-park-area',
  POKEMON_COLOR_LIST: '/pokemon-color',
  POKEMON_FORM_LIST: '/pokemon-form',
  POKEMON_HABITAT_LIST: '/pokemon-habitat',
  POKEMON_SHAPE_LIST: '/pokemon-shape',
  VERSION_LIST: '/version',
  VERSION_GROUP_LIST: '/version-group',
  EFFECT_LIST: '/effect',
  EFFECT_CHANCE_LIST: '/effect-chains',
};