[build]
  base = "react-pokemon-client"
  command = "yarn install --frozen-lockfile && yarn build"
  publish = "dist"
[build.environment]
  NODE_VERSION = "22.16.0"
  YARN_VERSION = "4.9.2"

[context.prev]
  command = "yarn install --frozen-lockfile && yarn build"
  # Add environment variables specific to qa if needed
  [context.prev.environment]
    NODE_ENV = "staging"

# Optional: Branch-specific settings for dev
[context.dev]
  command = "yarn install --frozen-lockfile && yarn build"
  # Add environment variables specific to dev if needed
  [context.dev.environment]
    NODE_ENV = "development"