name: Update PR with Issue Numbers

on:
     pull_request:
          types: [opened, synchronize, reopened]

permissions:
     issues: write
     pull-requests: write

jobs:
     update-pr:
          runs-on: ubuntu-latest
          steps:
               - uses: actions/checkout@v4
                 with:
                      ref: ${{ github.event.pull_request.head.ref }} # Checkout the PR's head branch
                      fetch-depth: 0 # Fetch all history

               - name: Fetch and process commit messages
                 id: process_commits
                 run: |
                      echo "Collecting commit messages..."
                      base_ref=${{ github.event.pull_request.base.ref }}
                      head_ref=${{ github.event.pull_request.head.ref }}
                      git fetch origin $base_ref $head_ref
                      commits=$(git log --pretty=%B origin/$base_ref..origin/$head_ref)
                      echo "Raw commit messages:"
                      echo "$commits"
                      body=""
                      echo "$commits" | while IFS= read -r commit; do
                        if [[ -z "$commit" ]]; then
                          continue
                        fi
                        # Replace (#<number>) with [#<number>](link)
                        modified_commit=$(echo "$commit" | sed -E 's|\(#[0-9]+\)|\[#\0\](https://github.com/${{ github.repository }}/issues/\0)|g' | sed -E 's|\(#([0-9]+)\)|#\1|g')
                        # Replace #<number> with [#<number>](link)
                        modified_commit=$(echo "$modified_commit" | sed -E 's|#[0-9]+|\[#\0\](https://github.com/${{ github.repository }}/issues/\0)|g')
                        body+="✅ $modified_commit\n"
                      done
                      if [[ -z "$body" ]]; then
                        echo "No commit messages found. Skipping update."
                        echo "skip=true" >> $GITHUB_OUTPUT
                        exit 0
                      fi
                      echo "generated_body<<EOF" >> $GITHUB_OUTPUT
                      echo -e "### These are the aggregated commits since last PR (auto-generated)\n$body" >> $GITHUB_OUTPUT
                      echo "EOF" >> $GITHUB_OUTPUT
                 env:
                      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

               - name: Update PR Description
                 if: steps.process_commits.outputs.skip != 'true'
                 uses: actions/github-script@v6
                 with:
                      github-token: ${{ secrets.GITHUB_TOKEN }}
                      script: |
                           const pr = context.payload.pull_request
                           const body = `${{ steps.process_commits.outputs.generated_body }}`
                           await github.rest.issues.update({
                             owner: context.repo.owner,
                             repo: context.repo.repo,
                             issue_number: pr.number,
                             body: body
                           })
