name: PR Description Aggregator

on:
     pull_request:
          types: [opened, synchronize, reopened]

permissions:
     issues: write
     pull-requests: write

jobs:
     update-pr-body:
          runs-on: ubuntu-latest

          steps:
               - name: Checkout repo
                 uses: actions/checkout@v4
                 with:
                      ref: ${{ github.event.pull_request.head.ref }} # Checkout the PR's head branch
                      fetch-depth: 0 # Fetch all history

               - name: Fetch commit messages
                 id: collect_commits
                 run: |
                      echo "Collecting commit messages..."
                      base_sha=$(gh pr view ${{ github.event.pull_request.number }} --json baseRefOid -q '.baseRefOid')
                      head_sha=$(gh pr view ${{ github.event.pull_request.number }} --json headRefOid -q '.headRefOid')
                      echo "Base SHA: $base_sha"
                      echo "Head SHA: $head_sha"
                      commits=$(git log --pretty=%B $base_sha..$head_sha)
                      echo "Raw commit messages:"
                      echo "$commits"
                      echo "commit_messages<<EOF" >> $GITHUB_OUTPUT
                      echo "$commits" >> $GITHUB_OUTPUT
                      echo "EOF" >> $GITHUB_OUTPUT
                 env:
                      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

               - name: Generate section for PR body
                 id: generate_body
                 run: |
                      header="These are the aggregated commits since last PR (auto-generated)"
                      body="### $header\n"
                      echo "${{ steps.collect_commits.outputs.commit_messages }}" | while IFS= read -r commit; do
                        if [[ -z "$commit" ]]; then
                          continue
                        fi
                        # Replace (#<number>) with [#<number>](link)
                        modified_commit=$(echo "$commit" | sed -E 's|\(#[0-9]+\)|\[#\0\](https://github.com/${{ github.repository }}/issues/\0)|g' | sed -E 's|\(#([0-9]+)\)|#\1|g')
                        # Replace #<number> with [#<number>](link)
                        modified_commit=$(echo "$modified_commit" | sed -E 's|#[0-9]+|\[#\0\](https://github.com/${{ github.repository }}/issues/\0)|g')
                        body+="✅ $modified_commit\n"
                      done
                      if [[ "$body" == "### $header\n" ]]; then
                        echo "No commit messages found. Skipping update."
                        echo "skip=true" >> $GITHUB_OUTPUT
                        exit 0
                      fi
                      echo "generated<<EOF" >> $GITHUB_OUTPUT
                      echo -e "$body" >> $GITHUB_OUTPUT
                      echo "EOF" >> $GITHUB_OUTPUT
                 env:
                      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

               - name: Replace PR description
                 if: steps.generate_body.outputs.skip != 'true'
                 run: |
                      gh pr edit ${{ github.event.pull_request.number }} \
                        --repo "${{ github.repository }}" \
                        --body "${{ steps.collect_commits.outputs.commit_messages }}"
                 env:
                      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
